// <auto-generated />
using alaska_airlines_test.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace alaskaairlinestest.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    [Migration("20171026033756_Create2")]
    partial class Create2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("alaska_airlines_test.Models.Airport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Airport");
                });

            modelBuilder.Entity("alaska_airlines_test.Models.Flight", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Arrives");

                    b.Property<DateTime>("Departs");

                    b.Property<int>("FirstClassPrice");

                    b.Property<int>("FlightNumber");

                    b.Property<int>("From");

                    b.Property<int>("MainCabinPrice");

                    b.Property<int>("To");

                    b.HasKey("ID");

                    b.ToTable("Flight");
                });
#pragma warning restore 612, 618
        }
    }
}
